### ISSUE TITLE
Create-react-app - Brunch version: Main issue

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1489]
[create-react-app](https://github.com/facebookincubator/create-react-app) is a new tool by Facebook that allows to easily create no-config react apps.

Brunch is much simpler & faster than webpack — and we should try to replace webpack in the tool. This issue is continuation of gh-1466.

![screen shot 2016-08-02 at 10 23 51 pm](https://cloud.githubusercontent.com/assets/943555/17332027/e82106dc-58ff-11e6-9e27-829a95fce3f5.png)
### Repositories
1. The skeleton that works already without `package.json` deps and brunch config: https://github.com/brunch/cra-brunch-test
2. The mediator that made the skeleton possible; alternative to `react-scripts`: https://github.com/brunch/cra-brunch
## First release

First and basic release after which i'm going to create the Pull Request to CRA should come with:
- [x] Basic babel with React (Aug 21)
- [x] Basic postcss with Autoprefixer (Aug 21)
- [ ] Basic ESLint [(WIP)](https://github.com/brunch/eslint-brunch/issues/11)
#### Milestone II
- [ ] Replicate all babel, postcss and eslint rules
- [ ] Ability to import CSS and SVG files. Need to clarify this one with Dan
#### Milestone III
- [ ] Environments support
- [ ] Babel environments support (`babel.dev.js`, `babel.prod.js`)
- [ ] `polyfills.js` inclusion
- [ ] HTML minifying
- [ ] Webserver improvements
#### Milestone IV
- [ ] `brunch build —production` should produce a html file with hashes appended to `.js` and `.css` sources
- [ ] `eject` script

**Comment by adrianmc** [comment]
Awesome work. I wish I was able to do more with my attempt, but unfortunately I'm still quite a newbie in the space. Which of the above features would you say would be doable for a newbie like myself?

**Comment by paulmillr** [comment]
Not much i'm afraid. I'll mention if there'll be something simple for the outside contributors.

**Comment by adrianmc** [comment]
It's also interesting that you created a new branch on the main Brunch repo in order to make this work. So I guess the official Brunch release, as it stands right now, is not quite flexible enough to do what you've done here?

**Comment by paulmillr** [comment]
yeah

**Comment by TheLarkInn** [comment]
If there are ways that we at webpack can give implementation ideas or strategies to help your efforts we'd be happy to. 

Conversely, we'd love to have the ideas and opinions from you guys to also help us improve webpack. If you guys have a great user configuration, we'd love some proposals for webpack as well. In the end there's always going to be multiple solutions to bundling etc. My goal in Webpack is to ensure that we make our solution at par for configuration and dev experience. Let me know your thoughts.

**Comment by paulmillr** [comment]
It's mostly philosophy. I have never been a fan of huge configuration files. The size of a popular Brunch config is about 5-10 LOC.

This is very detailed and not useful: [webpack.dev.js](https://github.com/facebookincubator/create-react-app/blob/master/config/webpack.config.dev.js). For example, why do I need to specify that JS should be processed with Babel? Instead of simply adding the plugin to `package.json`. Or, postcss.

**Comment by goshakkk** [comment]
@TheLarkInn the out-of-box speed, too. With Brunch (and quite a bit of plugins) it usually didn't take more than cmd-tab from vim to the browser to see my changes there. The project I'm currently working on is using webpack, I appreciate how powerful and fine-tuned to each particular use case webpack can be, but in terms of build times what I'm seeing is, after I cmt-tab to the browser, I get enough time to catch up on twitter while waiting for the build to finish.

That probably can somehow be optimized on a case by case basis by webpack gurus, but I take it most webpack users aren't.

**Comment by TheLarkInn** [comment]
I appreciate both of these responses!! I'm still watching and will follow up with you guys.

**Comment by lucasmreis** [comment]
One of the big problems of create-react-app is dealing with the complexity of the build process after `eject`. It's amazing that a version of it with Brunch is being developed! (and genius marketing move for Brunch itself 😄 )

**Comment by paulmillr** [comment]
Focusing on other issues for now
